---
all:
  vars:
    ansible_connection: ssh
    ansible_user: azureuser
    ansible_become: true
    ansible_become_user: root
    ansible_become_password: ZAQ!XSW@zaq1xsw2
    ansible_ssh_private_key_file: /home/azureuser/.ssh/id_rsa
    ansible_ssh_common_args: -o StrictHostKeyChecking=no

    # Deploy using the offline archive mode
    installation_method: archive
    confluent_archive_file_source: /home/azureuser/confluent-packages/confluent-7.9.1.tar.gz
    confluent_archive_file_remote: false

    # Enable JMX Exporter
    #####jmxexporter_enabled: true
    #####jmxexporter_url_remote: false
    #####jmxexporter_jar_url: /home/azureuser/confluent-packages/jmx_prometheus_javaagent-0.12.0.jar

    # #### SSL Configuration ####
    # # yamllint disable
    # # Prerequisite: Must install rng-tools since standard FIPS installations do not have enough randomness
    # # Note: if the SSL connections are flaky, check for HBSS blocking access to the files
    # #
    # # Must supply a Full chain for the certs provided. This must include the ROOT(s) and all the intermediates from
    # # the provided cert up to the ROOT(s). Failure to supply a full keychain will break BouncyCastle verification
    # # and SSL will fail which will bring down the broker.
    # # yamllint enable
    # ssl_custom_certs: true
    # ssl_ca_cert_filepath: "/some/path/full-trust-bundle.cert"
    # ssl_signed_cert_filepath: "/some/path/full-trust-bundle.cert"
    # # ^^^^ Must be a full chain of certs ^^^^
    # ssl_key_filepath: "/some/path/DataDisorder.key"
    # # ssl_key_password: {{enter_password}}

    #### Keystore/Truststore Configuration ####
    # keystore_storepass: secureKeystore
    # truststore_storepass: secureTruststore
    # kafka_broker_keystore_storepass: secureKeystore
    # kafka_broker_truststore_storepass: secureTruststore
    # #kafka_broker_keystore_storepass: "{{ keystore_storepass }}"
    # #kafka_broker_truststore_storepass: "{{ truststore_storepass }}"
    # schema_registry_keystore_storepass: "{{ keystore_storepass }}"
    # schema_registry_truststore_storepass: "{{ truststore_storepass }}"
    # kafka_connect_keystore_storepass: "{{ keystore_storepass }}"
    # kafka_connect_truststore_storepass: "{{ truststore_storepass }}"
    # ksql_keystore_storepass: "{{ keystore_storepass }}"
    # ksql_truststore_storepass: "{{ truststore_storepass }}"
    # control_center_keystore_storepass: "{{ keystore_storepass }}"
    # control_center_truststore_storepass: "{{ truststore_storepass }}"

    # #### Certificate Regeneration ####
    # regenerate_ca: false
    # regenerate_keystore_and_truststore: true

    #### Custom Yum Repo File (Rhel/Centos) ####
    # yamllint disable
    # confluent_common_repository_baseurl: "https://packages.confluent.io"
    # confluent_common_repository_redhat_dist_baseurl: "{{confluent_common_repository_redhat_baseurl}}/{{confluent_repo_version}}/7"
    # yamllint enable


kafka_controller:
  hosts: 10.0.0.5

####
# ██╗  ██╗ █████╗ ███████╗██╗  ██╗ █████╗
# ██║ ██╔╝██╔══██╗██╔════╝██║ ██╔╝██╔══██╗
# █████╔╝ ███████║█████╗  █████╔╝ ███████║
# ██╔═██╗ ██╔══██║██╔══╝  ██╔═██╗ ██╔══██║
# ██║  ██╗██║  ██║██║     ██║  ██╗██║  ██║
# ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝  ╚═╝╚═╝  ╚═╝
kafka_broker:
  vars:
    kafka_broker_custom_properties:
      confluent.support.metrics.enable: false

  hosts:
    10.0.0.5:
      broker_id: 1
      kafka_broker:
        properties:
          # yamllint disable
          offsets.topic.replication.factor: 1
          transaction.state.log.replication.factor: 1
          transaction.state.log.min.isr: 1
          confluent.license.topic.replication.factor: 1
          confluent.metadata.topic.replication.factor: 1
          confluent.telemetry.enabled: false
          confluent.balancer.enable: false
          metric.reporters: io.confluent.metrics.reporter.ConfluentMetricsReporter
          confluent.metrics.reporter.topic.replicas: 1
          # yamllint enable

####
# ███████╗ ██████╗██╗  ██╗███████╗███╗   ███╗ █████╗
# ██╔════╝██╔════╝██║  ██║██╔════╝████╗ ████║██╔══██╗
# ███████╗██║     ███████║█████╗  ██╔████╔██║███████║
# ╚════██║██║     ██╔══██║██╔══╝  ██║╚██╔╝██║██╔══██║
# ███████║╚██████╗██║  ██║███████╗██║ ╚═╝ ██║██║  ██║
# ╚══════╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝     ╚═╝╚═╝  ╚═╝
#
# ██████╗ ███████╗ ██████╗ ██╗███████╗████████╗██████╗ ██╗   ██╗
# ██╔══██╗██╔════╝██╔════╝ ██║██╔════╝╚══██╔══╝██╔══██╗╚██╗ ██╔╝
# ██████╔╝█████╗  ██║  ███╗██║███████╗   ██║   ██████╔╝ ╚████╔╝
# ██╔══██╗██╔══╝  ██║   ██║██║╚════██║   ██║   ██╔══██╗  ╚██╔╝
# ██║  ██║███████╗╚██████╔╝██║███████║   ██║   ██║  ██║   ██║
# ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝╚══════╝   ╚═╝   ╚═╝  ╚═╝   ╚═╝
#
schema_registry:
  hosts:
    10.0.0.5:


####
# ██╗  ██╗ █████╗ ███████╗██╗  ██╗ █████╗
# ██║ ██╔╝██╔══██╗██╔════╝██║ ██╔╝██╔══██╗
# █████╔╝ ███████║█████╗  █████╔╝ ███████║
# ██╔═██╗ ██╔══██║██╔══╝  ██╔═██╗ ██╔══██║
# ██║  ██╗██║  ██║██║     ██║  ██╗██║  ██║
# ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝  ╚═╝╚═╝  ╚═╝
#
#  ██████╗ ██████╗ ███╗   ██╗███╗   ██╗███████╗ ██████╗████████╗
# ██╔════╝██╔═══██╗████╗  ██║████╗  ██║██╔════╝██╔════╝╚══██╔══╝
# ██║     ██║   ██║██╔██╗ ██║██╔██╗ ██║█████╗  ██║        ██║
# ██║     ██║   ██║██║╚██╗██║██║╚██╗██║██╔══╝  ██║        ██║
# ╚██████╗╚██████╔╝██║ ╚████║██║ ╚████║███████╗╚██████╗   ██║
#  ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝  ╚═══╝╚══════╝ ╚═════╝   ╚═╝


kafka_connect:
  # vars:
  #   kafka_connect_plugins_path:
  #   - /usr/share/java, /usr/share/java/connect_plugins
  hosts:
    10.0.0.5:


####
# ██╗  ██╗███████╗ ██████╗ ██╗     ██████╗ ██████╗
# ██║ ██╔╝██╔════╝██╔═══██╗██║     ██╔══██╗██╔══██╗
# █████╔╝ ███████╗██║   ██║██║     ██║  ██║██████╔╝
# ██╔═██╗ ╚════██║██║▄▄ ██║██║     ██║  ██║██╔══██╗
# ██║  ██╗███████║╚██████╔╝███████╗██████╔╝██████╔╝
# ╚═╝  ╚═╝╚══════╝ ╚══▀▀═╝ ╚══════╝╚═════╝ ╚═════╝

ksql:
  hosts:
    10.0.0.5:


####
#  ██████╗ ██████╗ ███╗   ██╗████████╗██████╗  ██████╗ ██╗
# ██╔════╝██╔═══██╗████╗  ██║╚══██╔══╝██╔══██╗██╔═══██╗██║
# ██║     ██║   ██║██╔██╗ ██║   ██║   ██████╔╝██║   ██║██║
# ██║     ██║   ██║██║╚██╗██║   ██║   ██╔══██╗██║   ██║██║
# ╚██████╗╚██████╔╝██║ ╚████║   ██║   ██║  ██║╚██████╔╝███████╗
#  ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝   ╚═╝   ╚═╝  ╚═╝ ╚═════╝ ╚══════╝
#
#  ██████╗███████╗███╗   ██╗████████╗███████╗██████╗
# ██╔════╝██╔════╝████╗  ██║╚══██╔══╝██╔════╝██╔══██╗
# ██║     █████╗  ██╔██╗ ██║   ██║   █████╗  ██████╔╝
# ██║     ██╔══╝  ██║╚██╗██║   ██║   ██╔══╝  ██╔══██╗
# ╚██████╗███████╗██║ ╚████║   ██║   ███████╗██║  ██║
#  ╚═════╝╚══════╝╚═╝  ╚═══╝   ╚═╝   ╚══════╝╚═╝  ╚═╝

control_center:
  hosts:
    10.0.0.5:
